<a href="https://colab.research.google.com/github/Kashifletslearn/Day-17-30/blob/main/Day_17_30.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Hello i am Kashif khan let's learn together

1.   Github   : https://github.com/Kashifletslearn/Day-17-30
2.   Linkedin : https://www.linkedin.com/in/kashifkhank/
3.   Gmail    : kashifdocument11@gmail.com





#For suggestions and improvement Email me


#<u>**Problem 1**</u>

### In this problem, we are going to calculate distances between some pairs of points :

### <u> Measures of distances </u>
* ### Euclidean Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)={\sqrt {(x_{1}-x_{2})^{2}+(y_{1}-y_{2})^{2}}}.}$

* ### Manhattan Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)=|x_{1}-x_{2}|+|y_{1}-y_{2}|}$


### Create a 2-D array of 10 points where the x-coordinates and the y-coordinates can take random integral values between 5 and 20.


### Next, create two 1-D arrays(one for  Euclidean distance and the other for  Manhattan distance) for these points


In [1]:
import numpy as np

In [2]:
# Creating the 10 points
points=np.random.randint(5,20,size=(10,2))
points

array([[ 9, 19],
       [12,  7],
       [14, 17],
       [ 6, 12],
       [ 9,  5],
       [14, 15],
       [ 8, 12],
       [ 7, 17],
       [ 8, 15],
       [12,  5]])

In [3]:

def manhattan_distance(point1,point2):
    """Calclates and returns Manhattan Distance"""
    x1,y1=point1
    x2,y2=point2
    return round((abs(x2-x1)+abs(y2-y1)),2)

manhattan_distances=[]
for i in range(10):
    inner_llist=[]
    for j in range(10):
        inner_llist.append(manhattan_distance(points[i],points[j]))
    manhattan_distances.append(np.asarray(inner_llist))
manhattan_distances=np.asarray(manhattan_distances)
print(manhattan_distances)

[[ 0 15  7 10 14  9  8  4  5 17]
 [15  0 12 11  5 10  9 15 12  2]
 [ 7 12  0 13 17  2 11  7  8 14]
 [10 11 13  0 10 11  2  6  5 13]
 [14  5 17 10  0 15  8 14 11  3]
 [ 9 10  2 11 15  0  9  9  6 12]
 [ 8  9 11  2  8  9  0  6  3 11]
 [ 4 15  7  6 14  9  6  0  3 17]
 [ 5 12  8  5 11  6  3  3  0 14]
 [17  2 14 13  3 12 11 17 14  0]]
